# Generated by Django 4.2.6 on 2023-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metra', '0003_routetodisplay_alter_service_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(choices=[(1, 'Outbound'), (2, 'Inbound')], max_length=12),
        ),
    ]
