# Generated by Django 4.2.6 on 2023-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metra', '0004_alter_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.IntegerField(choices=[(1, 'Outbound'), (2, 'Inbound')]),
        ),
    ]
