# Generated by Django 4.2.6 on 2023-10-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metra', '0005_alter_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
